<a href="https://colab.research.google.com/github/saleemshad/Full-Stack-AI-ML/blob/main/Numpy_practice_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Import numpy as np and see the version

In [2]:
import numpy as np
print(np.__version__)

1.19.5


2. How to create a 1D array?

In [21]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. How to create a boolean array?
Create a 3×3 numpy array of all True’s

In [ ]:
arr = np.full((3,3), True, dtype=bool)
arr

In [18]:
arr = np.full((3,3), 1, dtype =int )
arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [19]:
arr = np.full((3,3), 2.0, dtype=float)
arr

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [36]:
arr = np.full((3,3), 'Shad', dtype='U4')
arr

array([['Shad', 'Shad', 'Shad'],
       ['Shad', 'Shad', 'Shad'],
       ['Shad', 'Shad', 'Shad']], dtype='<U4')

In [37]:
arr = np.full((3,3), 'Shad', dtype='S4')
arr

array([[b'Shad', b'Shad', b'Shad'],
       [b'Shad', b'Shad', b'Shad'],
       [b'Shad', b'Shad', b'Shad']], dtype='|S4')

4. How to extract items that satisfy a given condition from 1D array?
xtract all odd numbers from arr Input:

In [42]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 ==1]

array([1, 3, 5, 7, 9])

In [43]:
arr[arr %2 ==0] #even number of the above given array

array([0, 2, 4, 6, 8])

5. How to replace items that satisfy a condition with another value in numpy array?
Difficulty Level: L1 Q. Replace all odd numbers in arr with -1 Input:

In [47]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2==1] =-1
arr


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])